version: 0.1

default:
  deploy:
    parameters:
      stack_name: 'integration-test'
      s3_bucket: integration-test-deployment
      resolve_s3: false
      confirm_changeset: true
      capabilities: CAPABILITY_NAMED_IAM
      disable_rollback: false
